version: '3.5'

services:
  app:
    build:
      context: .
      target: dev
      cache_from:
        - ${IMAGE_BUILD:-snowballgr:latest}
    image: ${IMAGE_BUILD:-snowballgr:latest}
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      SERVICE_MONGODB_URI: mongodb://root:localdev@mongo:27017/?ssl=false
    volumes:
      - ".:/app/"
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: localdev
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"
